// <auto-generated />
using System;
using AvaliacaoCursoFormacao.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AvaliacaoCursoFormacao.Migrations
{
    [DbContext(typeof(CursoContext))]
    [Migration("20200718195641_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AvaliacaoCursoFormacao.Model.Categoria", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descricao");

                    b.HasKey("id");

                    b.ToTable("Categorias","dbo");
                });

            modelBuilder.Entity("AvaliacaoCursoFormacao.Model.Curso", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("categoriaid");

                    b.Property<DateTime>("dataFim");

                    b.Property<DateTime>("dataInicio");

                    b.Property<string>("descricao");

                    b.Property<int>("qtdAluno");

                    b.HasKey("id");

                    b.HasIndex("categoriaid");

                    b.ToTable("Cursos","dbo");
                });

            modelBuilder.Entity("AvaliacaoCursoFormacao.Model.Curso", b =>
                {
                    b.HasOne("AvaliacaoCursoFormacao.Model.Categoria", "categoria")
                        .WithMany("cursos")
                        .HasForeignKey("categoriaid")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
